### ISSUE TITLE
icon component (new)

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-community-ui-toolkit#12]
Create the `vscode-icon` component, which can be used to show an icon from the VS Code icons (https://github.com/microsoft/vscode-codicons).

Attributes:

- `name`: the name of the icon
- `size`: the height and width of the icon (optional)

**Comment by d13** [comment]
I'd like to take this one

**Comment by estruyf** [comment]
Great 👍, I'll assign it to you. Thanks for contributing 🙏
