### ISSUE TITLE
Create a sample extension for testing

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-community-ui-toolkit#15]
To test the web components during the development phase, a simple extension that loads a view with them in action in VS Code would be useful.

Similar to the dev server we have now running on `https://localhost:8000`.

**Comment by idoprz** [comment]
I think there is a difference between sample extension which needs a bundled version (also in future get it from npm) to a development/testing environment where you take it from the local server.
I can look into it. Do you think it should be an option in the sample extension? Or should it be another "dev" extension?

**Comment by estruyf** [comment]
If it was only intended as a sample it is fine for the future, but as the dev ext version would be more useful atm. That is why I thought is was related to this one. 

I'll check out the sample once I'm behind the computer.

**Comment by idoprz** [comment]
You can assign me to the dev extension then. I think I will do it as another extension.

**Comment by idoprz** [comment]
Just made a PR https://github.com/estruyf/vscode-community-ui-toolkit/pull/27
